version: "2"

services:

  php72:
    # image: connectivdocker/php:7.2
    build: ./docker/php72
    container_name: liris-php72
    networks:
      internal:
        ipv4_address: 172.23.0.72
    links:
    - mysql
    volumes:
    - ./:/var/www/html/liris
    restart: always


  httpd:
    image: httpd:2.4.33-alpine
    container_name: liris-httpd
    networks:
      internal:
        ipv4_address: 172.23.0.89
    volumes:
    - ./docker/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    - ./docker/conf/virtualhosts:/usr/local/apache2/conf/extra/vhosts
    - ./docker/conf/ssl:/usr/local/apache2/ssl
    - ./docker/logs/httpd:/var/log/httpd
    links:
    - php72
    volumes_from:
    - php72
    restart: always

  mysql:
    image: connectivdocker/mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker
    networks:
      internal:
        ipv4_address: 172.23.0.3
    volumes:
      - ./docker/database:/var/lib/mysql
    restart: always

networks:
  internal:
    ipam:
      config:
        - subnet: 172.23.0.0/16